image: registry.choerodon.com.cn/tools/cibase:0.5.0

stages:
  - package
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive

node-build:
  image: registry.choerodon.com.cn/tools/cifront:0.5.0
  stage: package
  script:
    - node_module_ci
    - node_build devbuild
    - rm -rf /cache/${CI_PROJECT_NAME}-${CI_PROJECT_ID}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
  only:
    - /^feature-.*$/


node-dev-build:
  image: registry.choerodon.com.cn/tools/cifront:0.5.0
  stage: package
  script:
    - node_module_ci
    - node_build build
    - cp -r dist /cache/${CI_PROJECT_NAME}-${CI_PROJECT_ID}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}/dist
  only:
    - develop
    - /^release-.*$/
    - /^hotfix-.*$/
    - tags

docker-build:
  stage: build
  script:
    - docker_build
    - rm -rf /cache/${CI_PROJECT_NAME}-${CI_PROJECT_ID}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
    - chart_build
  only:
    - develop
    - /^release-.*$/
    - /^hotfix-.*$/
    - tags

.auto_devops: &auto_devops |
  curl -o .auto_devops.sh \
      "${CHOERODON_URL}/devops/ci?token=${Token}&type=front"
  if [ $? -ne 0 ];then
    cat .auto_devops.sh
    exit 1
  fi
  source .auto_devops.sh

  function node_module_ci() {
    mkdir -p /cache/$CI_PROJECT_NAME-$CI_PROJECT_ID-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA/
    cp -fr ./choerodon-front-devops/devops ./choerodon-front-iam
    cd choerodon-front-iam
    python ./boot/structure/configAuto.py iam devops
    cp -r config.yml /cache/$CI_PROJECT_NAME-$CI_PROJECT_ID-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA/
    chmod 777 ./boot/structure/moduleCi.sh && ./boot/structure/moduleCi.sh boot iam devops
    cd boot
  }

  function node_build() {
    ./node_modules/.bin/gulp start
    npm run ${1:-"build"}
    find dist -name '*.js' | xargs sed -i "s/localhost:version/$CI_COMMIT_TAG/g"
  }

before_script:
  - *auto_devops