image: registry.choerodon.com.cn/tools/cibase:0.5.0

stages:
  - package
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive

node-build:
  image: registry.choerodon.com.cn/tools/cifront:0.5.0
  stage: package
  script:
    - node_module_ci
    - node_build build
    - rm -rf /cache/${CI_PROJECT_NAME}-${CI_PROJECT_ID}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
  only:
    - /^feature-.*$/


node-dev-build:
  image: registry.choerodon.com.cn/tools/cifront:0.5.0
  stage: package
  script:
    - node_module_ci
    - node_build build
    - cp -r dist /cache/${CI_PROJECT_NAME}-${CI_PROJECT_ID}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}/dist
    - cp -r node_modules/choerodon-front-boot/structure /cache/${CI_PROJECT_NAME}-${CI_PROJECT_ID}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}/structure
  only:
    - develop
    - /^release-.*$/
    - /^hotfix-.*$/
    - tags

docker-build:
  stage: build
  script:
    - docker_build
    - rm -rf /cache/${CI_PROJECT_NAME}-${CI_PROJECT_ID}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
    - chart_build
  only:
    - develop
    - /^release-.*$/
    - /^hotfix-.*$/
    - tags

.auto_devops: &auto_devops |
  curl -o .auto_devops.sh \
      "${CHOERODON_URL}/devops/ci?token=${Token}&type=front"
  if [ $? -ne 0 ];then
    cat .auto_devops.sh
    exit 1
  fi
  source .auto_devops.sh

  function node_module_ci() {
    npm install -registry https://nexus.choerodon.com.cn/repository/choerodon-npm/
    mkdir -p /cache/$CI_PROJECT_NAME-$CI_PROJECT_ID-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA/
    mkdir -p /tmp/
    cp -r ./node_modules/structure/configAuto.py /tmp/
    cd choerodon-front-iam
    cp -r ./iam/src/app/iam/config/ /tmp/
    cd ../choerodon-front-devops
    cp -r ./devops/src/app/devops/config/ /tmp/
    cd ../tmp
    python ./configAuto.py iam devops
    cp -r config.yml /cache/$CI_PROJECT_NAME-$CI_PROJECT_ID-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA/
    cd ..
  }

  function node_build() {
    chmod -R 777 node_modules
    npm run ${1:-"build"} choerodon-front-iam/iam choerodon-front-devops/devops -registry https://nexus.choerodon.com.cn/repository/choerodon-npm/
    find dist -name '*.js' | xargs sed -i "s/localhost:version/$CI_COMMIT_TAG/g"
  }

before_script:
  - *auto_devops