image: registry.cn-hangzhou.aliyuncs.com/choerodon-tools/cibase:0.8.1

stages:
  - package
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test_build:
  stage: package
  script:
    - node_module_ci
    - node_build linux_build
    - cp_file
    - docker_build
  only:
    - master

build:
  stage: package
  script:
    - node_module_ci
    - node_build linux_build
    - cp_file
    - docker_build push
  only:
    - tags

release:
  stage: build
  script:
    - chart_build
  only:
    - tags


.auto_devops: &auto_devops |
  http_status_code=`curl -o .auto_devops.sh -s -m 10 --connect-timeout 10 -w %{http_code} "${CHOERODON_URL}/devops/ci?token=${Token}&type=front"`
  if [ "$http_status_code" != "200" ]; then
    cat .auto_devops.sh
    exit 1
  fi
  source .auto_devops.sh

  function node_module_ci() {
    modules=(iam devops agile testManager wiki issue)
    folers=(choerodon-front-iam choerodon-front-devops choerodon-front-agile choerodon-front-test-manager choerodon-front-wiki choerodon-front-issue)

    npm i --registry https://nexus.choerodon.com.cn/repository/choerodon-npm/ --sass-binary-site=http://npm.taobao.org/mirrors/node-sass
    mkdir -p ./tmp/
    cp -r ./node_modules/choerodon-front-boot/structure ./tmp/structure
    
    for i in "${!modules[@]}"; 
    do 
      mkdir -p ./tmp/${modules[$i]}/src/app/${modules[$i]}/
      cp -r ./${folers[$i]}/${modules[$i]}/src/app/${modules[$i]}/config ./tmp/${modules[$i]}/src/app/${modules[$i]}/
    done

    cd ./tmp
    python ./structure/menu/__init__.py -o yml -m ${modules[@]}
    python ./structure/dashboard/__init__.py -o yml -m iam devops agile testManager wiki
    cd ..
  }

  function node_build() {
    chmod -R 777 node_modules
    modules=(choerodon-front-iam/iam choerodon-front-devops/devops choerodon-front-agile/agile choerodon-front-test-manager/testManager choerodon-front-wiki/wiki choerodon-front-issue/issue)
 
    npm run ${1:-"build"} ${modules[@]} -registry https://nexus.choerodon.com.cn/repository/choerodon-npm/  --sass-binary-site=http://npm.taobao.org/mirrors/node-sass --loglevel verbose
    find dist -name '*.js' | xargs sed -i "s/localhost:version/$CI_COMMIT_TAG/g"
  }

  function cp_file(){
    cd $CI_PROJECT_DIR
    
    mkdir -p $CI_PROJECT_DIR/docker
    cp -r Dockerfile $CI_PROJECT_DIR/docker
    cp -r node_modules/choerodon-front-boot/structure $CI_PROJECT_DIR/docker/structure
    cp -r parent-structure $CI_PROJECT_DIR/docker/parent-structure
    cp -r ./tmp/menu.yml $CI_PROJECT_DIR/docker
    cp -r ./tmp/dashboard.yml $CI_PROJECT_DIR/docker
    cp -r dist $CI_PROJECT_DIR/docker/dist

    rm -rf ./tmp
  }

  function docker_build(){
    sed -i "s/registry\.cn\-hangzhou\.aliyuncs.com\/choerodon-tools/choerodon/g" Dockerfile
    docker login -u ${REGISTRY_USER} -p ${REGISTRY_PASSWORD}
    docker build --pull -t choerodon/choerodon-front:${CI_COMMIT_TAG} .
    if [ "$1" eq "push" ]; then
      docker push choerodon/choerodon-front:${CI_COMMIT_TAG}
    fi
  }

  function chart_build(){
    CHART_PATH=`find . -name Chart.yaml`
    yq w -i ${CHART_PATH%/*}/values.yaml image.repository choerodon/choerodon-front
    yq w -i ${CHART_PATH%/*}/values.yaml image.tag ${CI_COMMIT_TAG}
    helm repo add choerodon "${CHART_REPOSITORY}/${CHART_ORGANIZATION}/${CHART_PROJECT}/"
    helm push --username ${HELM_USER} --password ${HELM_PASSWORD} ${CHART_PATH%/*} --version ${CI_COMMIT_TAG} choerodon
  }

before_script:
  - *auto_devops
