image: registry.choerodon.com.cn/tools/cibase:0.5.0

stages:
  - package
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive

node-build:
  image: registry.choerodon.com.cn/tools/cifront:0.5.0
  stage: package
  script:
    - node_module_ci
    - node_build build
    - rm -rf /cache/${CI_PROJECT_NAME}-${CI_PROJECT_ID}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
  only:
    - /^feature-.*$/


node-dev-build:
  image: registry.choerodon.com.cn/tools/cifront:0.5.0
  stage: package
  script:
    - node_module_ci
    - node_build build
    - cp -r dist /cache/${CI_PROJECT_NAME}-${CI_PROJECT_ID}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}/dist
    - cp -r node_modules/choerodon-front-boot/structure /cache/${CI_PROJECT_NAME}-${CI_PROJECT_ID}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}/structure
    - cp -r parent-structure /cache/${CI_PROJECT_NAME}-${CI_PROJECT_ID}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}/parent-structure
  only:
    - develop
    - /^release-.*$/
    - /^hotfix-.*$/
    - tags

docker-build:
  stage: build
  script:
    - docker_build
    - rm -rf /cache/${CI_PROJECT_NAME}-${CI_PROJECT_ID}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
    - chart_build
  only:
    - develop
    - /^release-.*$/
    - /^hotfix-.*$/
    - tags

.auto_devops: &auto_devops |
  curl -o .auto_devops.sh \
      "${CHOERODON_URL}/devops/ci?token=${Token}"
  if [ $? -ne 0 ];then
    cat .auto_devops.sh
    exit 1
  fi
  source .auto_devops.sh

  function node_module_ci() {
    npm install -registry https://nexus.choerodon.com.cn/repository/choerodon-npm/
    mkdir -p /cache/$CI_PROJECT_NAME-$CI_PROJECT_ID-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA/
    mkdir -p ./tmp/
    cp -r ./node_modules/choerodon-front-boot/structure/configAuto.py ./tmp/
    modules=(iam devops agile testManager wiki)
    folers=(choerodon-front-iam choerodon-front-devops choerodon-front-agile choerodon-front-test-manager choerodon-front-wiki)
    for i in "${!modules[@]}"; 
    do 
      mkdir -p ./tmp/${modules[$i]}/src/app/${modules[$i]}/
      cp -r ./${folers[$i]}/${modules[$i]}/src/app/${modules[$i]}/config ./tmp/${modules[$i]}/src/app/${modules[$i]}/
    done
    cd ./tmp
    python ./configAuto.py ${modules[@]}
    cp -r config.yml /cache/$CI_PROJECT_NAME-$CI_PROJECT_ID-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA/
    rm -rf ./tmp
  }

  function node_build() {
    chmod -R 777 node_modules
    npm run ${1:-"build"} choerodon-front-iam/iam choerodon-front-devops/devops choerodon-front-agile/agile -registry https://nexus.choerodon.com.cn/repository/choerodon-npm/
    find dist -name '*.js' | xargs sed -i "s/localhost:version/$CI_COMMIT_TAG/g"
  }

  function docker_build(){
    cp -r /cache/${CI_PROJECT_NAME}-${CI_PROJECT_ID}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}/* ${1:-"."}
    docker build --pull -t ${DOCKER_REGISTRY}/${GROUP_NAME}/${PROJECT_NAME}:${CI_COMMIT_TAG} ${1:-"."}
    docker push ${DOCKER_REGISTRY}/${GROUP_NAME}/${PROJECT_NAME}:${CI_COMMIT_TAG}
  }

before_script:
  - *auto_devops